### ISSUE TITLE
close() method

### ISSUE THREAD

**Issue by tpd001** [kamakazikamikaze/easysnmp#46]
Hi, thanks for working on this very useful body of code.

We are trying to issue GET requests for 12 OIDs to about 170 devices, using Python process-based multiprocessing (mp.Pool(), pool.apply_async()), set up to run between 4- and 32-way parallel.  We previously tried multithreading but ran into inconsistencies in the results (specifically, returned VarBinds missing OIDs, the values may have been correct; but this is another topic).

After creating around 90 sessions we run into some resource limit and are unable to collect from the remaining 80 or so devices.

After some experimentation we added a Session.close() method and modified the Session.**del**() method to check the self.sess_ptr against None.   Calling Session.close() after each GET allows us to read all target devices without encountering the resource limit.

Here's the relevant section of session.py:

```
  def close(self):
        if self.sess_ptr is not None:
            status = interface.delete_session(self)
            self.sess_ptr = None
        return status

    def __del__(self):
        """Deletes the session and frees up memory"""
        if self.sess_ptr is not None:
            status = interface.delete_session(self)
            self.sess_ptr = None
        return
```

Please let us know what you think of this.

Also, a detail, the descriptive string for the Python delete_session method in interface.c is incorrect:

```
    {
            "delete_session",
            netsnmp_delete_session,
            METH_VARARGS,
            "create a netsnmp session."
        },
```

Best
Tim

**Comment by kamakazikamikaze** [comment]
These memory issues are related to #21 and could be fixed along with #30 (as well as dropped varbinds) if I can ever get around to studying on PyCapsules and shifting the code over to them.

**Comment by kamakazikamikaze** [comment]
@tpd001 I'm currently reviewing some work that another contributor had started but was not able to fully test and merge to the main branch. After I've run some tests on it, I will see if this snippet is necessary and try it out.

As for the resource limit, we had run into that before as well. Was your script set up to run "forever" in the background?

Our script was daemonized to run every 5 minutes, however Python would not release the memory back to the system which caused it to crash after 17 hours. Eventually we set it to be called by `cron` every five minutes to run `walk` on a limited number of MIB trees for our wireless APs. We have a pool of 100 workers running asynchronously through all 3,300 (and counting!) devices, sending the data to ElasticSearch, then it terminates. The memory is finally released back to the system when complete. I don't know how you have it set up, but a temporary workaround -- should you run into issues again -- may be to invoke the script multiple times instead of having it loop/run continuously.

**Comment by kamakazikamikaze** [comment]
Ok, I've revised the code and I believe I've plugged a leak. However, I need some help performing additional tests. While I was able to plug the leak (in `bulkwalk`), I think a few OIDs may be getting pruned but I'm querying so high up the tree that it may just be the switch struggling to keep up. Would you be willing to download and beta-test for me?

[This is the commit.](https://github.com/kamakazikamikaze/easysnmp/commit/c0815a430bf76c7351ba2ac476b57129288b0276) Please do not hesitate to reply with any comments, questions, or criticism

**Comment by tpd001** [comment]
Hi, thanks for working on this.  To answer your question:  Our code is invoked periodically and exited when complete.  A new Linux process and Python interpreter is instantiated each time.

The changes I supplied work well for our application, when Python multiprocessing is used.  I would not expect the changes I supplied to have any impact on the behavior of the application when coded to use Python multi-threading, but I could be mistaken.

Regarding your commit, I see two major functional changes:

1. Removal of the netsnmp_delete_method().  I'm not sure why this was required, and why a corresponding change was not made to interface.c.   Does this impact the change I provided and, if so, how?  (Seems like it would negate it).

2. If the call to PyDECREF was causing the memory leak then inspection would suggest the leak has been fixed.

Regarding testing, if the client is not receiving all of the OIDs requested before the timeout expires then it should be returning some sort of error code.  You should be able to see what the switch sent in various ways.  I may still have my test program around, I will let you know later today.

Thanks!

**Comment by kamakazikamikaze** [comment]
Thanks for volunteering some time to test it. I look forward to hearing back from you.

Regarding your first comment on the changes, let me first say that I'm not an official contributor to this package and I'm still learning Python and its C API, and as such I'm operating mostly off of what patterns I've observed and what I've researched. From what I was able to see, `sess_ptr` was only being closed but not released back into the system. I guess I could have tested this by trying to free it up in the C function:

```C
static PyObject *netsnmp_delete_session(PyObject *self, PyObject *args)		
 {		
     PyObject *session;		
     SnmpSession *ss = NULL;		
 		
     if (!PyArg_ParseTuple(args, "O", &session))		
     {		
         return NULL;		
     }		

     ss = (SnmpSession *)py_netsnmp_attr_void_ptr(session, "sess_ptr");		
 
     snmp_sess_close(ss);
     /* Possibly call 'free' here and observe the effect */
     return (Py_BuildValue(""));		
 }
```
reflecting off the fact you needed to include `self.sess_ptr = None` on the Python side.

PyCapsules/CObjects were refactored to handle this a little differently. They, too, close the session but there is a call to `free` in them:

```C
#ifdef USE_DEPRECATED_COBJECT_API
/* The CObject API calls destructor with stored pointer */
    static void delete_session_capsule(void *session_ptr)
    {
        struct session_capsule_ctx *ctx = session_ptr;
        if (ctx)
        {
            snmp_sess_close(ctx->handle);
            free(ctx);  //<-----
        }
    }
#else
    /* Automatically called when Python reclaims session_capsule object. */
    static void delete_session_capsule(PyObject *session_capsule)
    {
        /* PyCapsule_GetPointer will raise an exception if it fails. */
        struct session_capsule_ctx *ctx = PyCapsule_GetPointer(session_capsule, NULL);
        if (ctx)
        {
            snmp_sess_close(ctx->handle);
            free(ctx);  //<-----
        }
    }
#endif /* USE_DEPRECATED_COBJECT_API */
```

*If* the code behaves in this manner then it is eliminating the need for you to set `self.sess_ptr = None` altogether, but when I have time later I will verify this manually.

**Comment by tpd001** [comment]
Hi again, the self.sess_ptr = None was required to allow the __del__() method to detect that the session had already been closed, calling snmp_sess_close() twice (remember the __del__() method is eventually called when the session object goes out of scope) results in a crash as the runtime system tries to free something twice.  Unless the underlying code tolerates passing NULL arguments you are going to need this.

**Comment by kamakazikamikaze** [comment]
Are you explaining why you had to include your provided `.close()` method? Or are you reporting that you're still needing to use it (and that my changes are causing a crash)? I just want to be certain

**Comment by tpd001** [comment]
Sorry for the lack of clarity.
The close() method was added for reasons explained in the initial issue comment I posted.
The close() method sets the self.sess_ptr to None so that when the _ _del_ _() method is later called (when the object goes out of scope), it can test the value of the self.sess_ptr and avoid calling interface.delete_session(self) again, e.g., after it was called as part of the close() processing.  If interface.delete_session(self) is called twice for the same session object bad things happen...
I have not tested your changes yet.  
Hope that helps.

**Comment by tpd001** [comment]
Hi again, I have not forgotten about this and should be able to get to it this week.  
I see some of my comments above are in error, apologies for that.

**Comment by kamakazikamikaze** [comment]
Thanks Tim. I've been experimenting some more with Heapy, ObjGraph, and PDB to see where else we may be experiencing memory leaks. I think I may be doing something wrong because ObjGraph is claiming that the SNMPVariable lists returned from the functions are also being leaked as they have an extra reference count on them. I'll have to dig a little deeper to verify this.

**Comment by tpd001** [comment]
I've tested the 'bulkwalk' branch content with my multi-threaded application but the library still returns VarBinds with missing OIDs.  So I don't think we've addressed that particular issue.  I did not look for signs of memory leaks.  

Moving forward I will continue to use the fgimian/easysnmp library combined with Python multiprocessing, either with or without the addition of the Session.close() method I implemented earlier.  Note the code I provided is incorrect in that the returned status value is not initialized if the passed session pointer is None.

**Comment by kamakazikamikaze** [comment]
Thanks Tim, sorry to hear that we're still seeing some issues. I'll assume that using `bulkwalk` isn't that much beneficial for you over `walk` for the time being as well. 

If you're not aware, I recently found out that you can set the life cycle of each worker in a pool so that memory is free'd back to the system sooner (if it matters with how many devices you're polling or how many OIDs you're requesting). Maybe that will help too to alleviate running out of system resources.

**Comment by kamakazikamikaze** [comment]
@tpd001 I'm not sure if you're still using this library or not but I've recently patched some issues regarding reference counters and some data not being `free`'d properly. Hopefully this will replace the need for a `.close()` method
